"""Predefined category names used for matching and filtering."""
categories = ["BRICK",
              "PLATE",
              "TILE",
              "SLOPE",
              "CURVED SLOPE",
              "CYLINDER",
              "DISH",
              "BAR",
              "FLEXIBLE",
              "PANEL",
              "ANIMAL",
              "PLANT",
              "BUILDING",
              "MINIFIGURE",
              "ACCESORY",
              "BASEPLATE",
              "VEHICLE",
              "MISCELLANEOUS",
              "LIFTARM",
              "CONNECTOR"]